import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const { chromium } = await import(process.env.SMARTJC_PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.SMARTJC_BASE_URL || 'http://127.0.0.1:5174/';
const output = join(tmpdir(), 'smartjc-checks');
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: process.env.SMARTJC_BROWSER || 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  console.log(await page.evaluate(async () => (await import('/tests/contracts.ts')).runContracts()));
  await page.goto(base + '#/fixture');
  const title = page.getByRole('textbox', { name: '幻灯片标题', exact: true });
  await title.fill('中文草稿');
  assert.equal(await title.evaluate(el => el === document.activeElement), true);
  await title.dispatchEvent('compositionstart', { data: '' });
  await title.fill('中文组合输入');
  assert.equal(await title.evaluate(el => el === document.activeElement), true);
  await title.dispatchEvent('compositionend', { data: '输入' });
  await page.locator('[data-slide-id="slide-2"]').click();
  await page.locator('[data-slide-id="slide-1"]').click();
  assert.equal(await title.innerText(), '中文组合输入');
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(await title.innerText(), '一个可追溯的研究结论');
  await page.getByRole('button', { name: '重做', exact: true }).click();
  assert.equal(await title.innerText(), '中文组合输入');
  await page.getByRole('button', { name: '下移本页', exact: true }).click();
  assert.equal(await page.locator('[data-slide-id][aria-current="page"]').getAttribute('data-slide-id'), 'slide-1');
  assert.deepEqual(await page.locator('[data-slide-id]').evaluateAll(els => els.map(el => el.dataset.slideId)), ['slide-2', 'slide-1', 'slide-3']);
  await page.locator('[data-slide-id="slide-2"]').click();
  await page.locator('[data-slide-preview="current"] [data-element-id="f1"]').click();
  await page.getByRole('button', { name: '删除选中元素', exact: true }).click();
  assert.equal(await page.getByRole('combobox', { name: '选择布局' }).inputValue(), 'text-only');
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  const fixtureDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出 PPTX', exact: true }).click();
  await (await fixtureDownload).saveAs(join(output, 'fixture.pptx'));
  for (let i = 0; i < 3; i++) await page.getByRole('button', { name: '删除本页', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: '导出 PPTX', exact: true }).isDisabled(), true);
  assert.equal(await page.locator('[data-slide-id]').count(), 0);
  await page.getByRole('button', { name: '撤销', exact: true }).click();
  assert.equal(await page.locator('[data-slide-id]').count(), 1);
  await page.getByRole('button', { name: '重做', exact: true }).click();
  await page.getByRole('button', { name: '新增页', exact: true }).first().click();
  assert.equal(await page.locator('[data-slide-id]').count(), 1);
  console.log('PASS: React draft/focus/composition/selection/reorder/undo/redo/empty/export');

  await page.goto(base);
  await page.getByLabel('选择论文 PDF').setInputFiles(resolve('test-fixtures/papers/mechanism-modt-cdifficile.pdf'));
  await page.waitForURL(/project/);
  await page.getByRole('button', { name: '解析论文', exact: true }).click();
  await page.getByText('已解析 32 页').waitFor({ timeout: 60000 });
  const id = page.url().split('/project/')[1];
  // M2 沿用同一 Deck fixture 注入开发标注；模型生成在后续阶段接入。
  await page.evaluate(async id => {
    const { loadProject } = await import('/src/storage.ts'); const { fixtureDeck, fixturePaper } = await import('/src/fixtures.ts');
    const data = await loadProject(id); const paper = structuredClone(data.paper);
    paper.sources.push(...structuredClone(fixturePaper.sources).map(source => ({ ...source, pageNumber: 8 })));
    paper.figures = structuredClone(fixturePaper.figures);
    const deck = { ...structuredClone(fixtureDeck), id: crypto.randomUUID(), paperId: paper.id };
    await new Promise((resolve, reject) => {
      const req = indexedDB.open('smartjc', 1); req.onsuccess = () => {
        const db = req.result; const tx = db.transaction(['papers', 'projects', 'decks'], 'readwrite');
        tx.objectStore('papers').put(paper, paper.id); tx.objectStore('decks').put(deck, deck.id);
        tx.objectStore('projects').put({ ...data.project, checkpoint: 'deck-ready', currentDeckId: deck.id }, id);
        tx.oncomplete = () => { db.close(); resolve(); }; tx.onabort = () => reject(tx.error);
      };
    });
  }, id);
  await page.reload();
  await page.locator('[data-slide-id="slide-2"]').click();
  await page.locator('[data-slide-preview="current"] [data-element-id="f1"]').click();
  await page.getByRole('button', { name: '裁图', exact: true }).click();
  await page.getByText('正在加载原页…').waitFor({ state: 'hidden' });
  assert.equal(await page.locator('canvas').evaluate(canvas => {
    const pixels = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data;
    let count = 0; for (let i = 0; i < pixels.length; i += 4) if (pixels[i] < 230 && pixels[i + 3] > 0) count++; return count > 1000;
  }), true);
  await page.screenshot({ path: join(output, 'source-desktop.png'), fullPage: true });
  const bounds = await page.locator('[data-pdf-page]').boundingBox();
  await page.mouse.move(bounds.x + bounds.width * .2, bounds.y + bounds.height * .25);
  await page.mouse.down(); await page.mouse.move(bounds.x + bounds.width * .7, bounds.y + bounds.height * .6, { steps: 8 }); await page.mouse.up();
  await page.getByRole('button', { name: '应用到本页', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  const saved = await page.evaluate(async id => (await (await import('/src/storage.ts')).loadProject(id)).deck, id);
  assert.ok(saved.slides[1].elements.find(e => e.id === 'f1').cropOverride);
  assert.equal(saved.slides[2].elements.find(e => e.id === 'f2').cropOverride, undefined);
  assert.equal(saved.revision, 1);
  const editingTitle = page.getByRole('textbox', { name: '幻灯片标题', exact: true });
  await page.evaluate(() => {
    window.__smartjcOriginalPut = IDBObjectStore.prototype.put;
    IDBObjectStore.prototype.put = function (...args) { if (this.name === 'decks') throw new DOMException('fixed failure', 'QuotaExceededError'); return window.__smartjcOriginalPut.apply(this, args); };
  });
  await editingTitle.fill('保存失败后仍保留的草稿');
  await page.getByRole('button', { name: '返回首页', exact: true }).click();
  await page.getByRole('button', { name: '重试保存', exact: true }).waitFor();
  assert.ok(page.url().includes('/project/'));
  assert.equal(await editingTitle.innerText(), '保存失败后仍保留的草稿');
  assert.equal(await page.evaluate(async id => (await (await import('/src/storage.ts')).loadProject(id)).deck.revision, id), 1);
  await page.evaluate(() => { IDBObjectStore.prototype.put = window.__smartjcOriginalPut; delete window.__smartjcOriginalPut; });
  await page.getByRole('button', { name: '重试保存', exact: true }).click();
  await page.getByRole('status').filter({ hasText: '已保存' }).waitFor();
  await page.reload();
  await page.locator('[data-slide-preview="current"] img').waitFor();
  assert.equal(await page.locator('[data-slide-id][aria-current="page"]').getAttribute('data-slide-id'), 'slide-2');
  assert.ok((await page.locator('[data-slide-preview="current"] img').getAttribute('src')).startsWith('data:image/png;base64,'));
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: '导出 PPTX', exact: true }).click();
  await (await download).saveAs(join(output, 'paper.pptx'));
  await page.screenshot({ path: join(output, 'editor-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: join(output, 'editor-mobile.png'), fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('PASS: PDF upload/parse/canvas/source/crop-isolation/save/reopen/rebuild/export/mobile');
  console.log('Artifacts:', output);
} finally { await browser.close(); }
