import './style.css';
import { fixtureDeck, fixturePaper, fixtureSource } from './fixtures';
import { computeLayout, validateDeck } from './layout';
import { createSlide, DeckSession } from './deck';
import { exportDeck } from './export';
import type { Element, Slide } from './types';

const app = document.querySelector<HTMLDivElement>('#app')!;
const placeholder = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="480"><rect width="800" height="480" fill="#e8eef2"/><text x="300" y="250" font-size="40" fill="#39718c">Figure 3</text></svg>');
const session = new DeckSession(fixtureDeck, fixturePaper);
let selected = 0; let selectedElementId: string | null = null; let status = '已保存';
const escapeHtml = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const button = (id: string, label: string, extra = '') => '<button id="' + id + '" class="button ' + extra + '">' + label + '</button>';
app.innerHTML = '<main class="app-shell"><header class="topbar"><div class="brand"><span class="brand-mark">JC</span><div><h1>smartJC</h1><p>可编辑的文献汇报 Deck</p></div></div><div class="top-actions"><span id="save-status" class="save-status"></span>' + button('export', '导出 PPTX', 'primary') + '<button id="more" class="icon-button" title="更多操作" aria-label="更多操作">⋯</button></div></header><div class="workspace"><aside class="sidebar"><div class="sidebar-head"><h2>幻灯片</h2>' + button('add-slide', '+ 新增页') + '</div><div id="slides" class="slide-list"></div><div class="sidebar-foot">拖动缩略图可调整顺序</div></aside><section class="editor"><div class="editor-head"><div><span class="eyebrow">当前页面</span><h2 id="slide-heading"></h2></div><div class="page-actions">' + button('delete-slide', '删除本页', 'quiet') + '</div></div><div id="stage" class="stage-wrap"></div><div class="editor-tools"><div class="tool-group"><span class="tool-label">布局</span><select id="layout-select" aria-label="选择布局"><option value="title">标题</option><option value="text-only">文字</option><option value="figure-full">单图</option><option value="figure-text">图文</option><option value="two-figures">双图</option><option value="panel-grid">Panel 网格</option></select></div><div id="selection-tools" class="selection-tools"></div><div class="tool-group undo-tools">' + button('undo', '撤销') + button('redo', '重做') + '</div></div><div id="status" class="status-line"></div></section><aside class="assistant"><div class="assistant-head"><div><span class="eyebrow">编辑摘要</span><h2>当前 Deck</h2></div><span class="revision" id="revision"></span></div><div class="summary-box"><strong>固定学术主题</strong><p>标题、图源和来源标签使用共享归一化布局，导出后文字仍是可编辑对象。</p></div><div class="source-box"><span class="eyebrow">来源</span><strong>PDF page ' + fixtureSource.pageNumber + '</strong><p>' + fixtureSource.id + ' · Figure 3</p></div><div class="assistant-note">选择文字后直接编辑，结束编辑会生成一条撤销记录。</div></aside></div></main>';
const slidesEl = document.querySelector<HTMLDivElement>('#slides')!; const stageEl = document.querySelector<HTMLDivElement>('#stage')!; const heading = document.querySelector<HTMLHeadingElement>('#slide-heading')!; const statusEl = document.querySelector<HTMLDivElement>('#status')!; const saveEl = document.querySelector<HTMLSpanElement>('#save-status')!; const revisionEl = document.querySelector<HTMLSpanElement>('#revision')!; const selectionEl = document.querySelector<HTMLDivElement>('#selection-tools')!; const layoutSelect = document.querySelector<HTMLSelectElement>('#layout-select')!; const undoButton = document.querySelector<HTMLButtonElement>('#undo')!; const redoButton = document.querySelector<HTMLButtonElement>('#redo')!;
function currentSlide() { return session.current.slides[selected]; }
function position(rect: { x:number; y:number; width:number; height:number }) { return 'left:' + rect.x * 100 + '%;top:' + rect.y * 100 + '%;width:' + rect.width * 100 + '%;height:' + rect.height * 100 + '%'; }
function editable(content: string, kind: string, id = '') { return '<div class="editable" contenteditable="true" spellcheck="false" data-edit-kind="' + kind + '" data-element-id="' + id + '">' + escapeHtml(content) + '</div>'; }
function renderElement(element: Element, rect: { x:number; y:number; width:number; height:number }) {
  const selectedClass = element.id === selectedElementId ? ' selected-element' : '';
  if (element.type === 'figure') return '<button class="figure-element' + selectedClass + '" data-element-id="' + element.id + '" style="' + position(rect) + '" title="选择 Figure"><img src="' + placeholder + '" alt="Figure 3" /></button>';
  if (element.type === 'citation') return '<div class="citation-element' + selectedClass + '" data-element-id="' + element.id + '" style="' + position(rect) + '">' + editable(element.sourceIds.map(id => '来源：' + id).join('；'), 'citation', element.id) + '</div>';
  if (element.type === 'bullet-list') return '<div class="text-element bullet-element' + selectedClass + '" data-element-id="' + element.id + '" style="' + position(rect) + '">' + element.items.map(item => '<div class="bullet-item">• ' + editable(item, 'bullet', element.id) + '</div>').join('') + '</div>';
  return '<div class="text-element' + selectedClass + '" data-element-id="' + element.id + '" style="' + position(rect) + '">' + editable(element.text, 'text', element.id) + '</div>';
}
function renderDeck() {
  const slide = currentSlide(); selectedElementId = slide?.elements.some(element => element.id === selectedElementId) ? selectedElementId : null;
  slidesEl.innerHTML = session.current.slides.map((item, index) => '<button draggable="true" class="slide-thumb ' + (index === selected ? 'active' : '') + '" data-index="' + index + '"><span class="thumb-number">' + String(index + 1).padStart(2, '0') + '</span><span class="thumb-title">' + escapeHtml(item.title || '无标题') + '</span><span class="thumb-kind">' + item.kind + '</span></button>').join('');
  slidesEl.querySelectorAll<HTMLButtonElement>('.slide-thumb').forEach(item => { item.onclick = () => { selected = Number(item.dataset.index); selectedElementId = null; renderDeck(); }; item.ondragstart = event => { event.dataTransfer?.setData('text/plain', item.dataset.index || '0'); }; item.ondragover = event => event.preventDefault(); item.ondrop = event => { event.preventDefault(); const from = Number(event.dataTransfer?.getData('text/plain')); const to = Number(item.dataset.index); if (from !== to) { try { session.commit({ type: 'deck' }, [{ type: 'move-slide', slideId: session.current.slides[from].id, afterSlideId: to === 0 ? null : session.current.slides[to].id }], '调整页顺序'); selected = to; status = '已保存'; renderDeck(); } catch (error) { status = error instanceof Error ? error.message : String(error); renderDeck(); } } }; });
  if (!slide) { heading.textContent = '暂无幻灯片'; stageEl.innerHTML = '<div class="empty-stage">没有幻灯片，新增一页开始编辑。</div>'; selectionEl.innerHTML = ''; layoutSelect.disabled = true; statusEl.textContent = '空 Deck 可继续编辑，但导出已禁用。'; return; }
  layoutSelect.disabled = false; layoutSelect.value = slide.layoutId; heading.textContent = slide.title || '无标题'; const layout = computeLayout(slide);
  stageEl.innerHTML = '<div class="stage-canvas"><div class="stage-title" style="' + position(layout.title) + '">' + editable(slide.title, 'title') + '</div>' + (layout.message ? '<div class="stage-message" style="' + position(layout.message) + '">' + editable(slide.message || '', 'message') + '</div>' : '') + layout.elements.map(item => renderElement(item.element, item.rect)).join('') + '<div class="source-label" style="' + position(layout.sourceLabel) + '">来源：PDF page 1 · ' + fixtureSource.id + '</div></div>';
  selectionEl.innerHTML = '<span class="tool-label">元素</span>' + button('add-text', '+ 文字') + button('add-list', '+ 列表') + button('add-citation', '+ 引用') + (selectedElementId ? button('delete-element', '删除选中', 'quiet') : '');
  revisionEl.textContent = 'revision ' + session.current.revision; saveEl.textContent = status; statusEl.textContent = validateDeck(session.current, fixturePaper).length ? '当前 Deck 校验失败' : '修改会自动保存到当前会话'; undoButton.disabled = !session.canUndo; redoButton.disabled = !session.canRedo; document.querySelector<HTMLButtonElement>('#delete-slide')!.disabled = false; document.querySelector<HTMLButtonElement>('#export')!.disabled = !session.current.slides.length;
  stageEl.querySelectorAll<HTMLElement>('[data-element-id]').forEach(node => node.onclick = event => { if ((event.target as HTMLElement).closest('.editable')) return; selectedElementId = node.dataset.elementId || null; renderDeck(); });
  stageEl.querySelectorAll<HTMLElement>('.editable').forEach(node => { node.dataset.original = node.textContent || ''; node.onblur = () => commitEdit(node); node.onkeydown = event => { if (event.key === 'Escape') { node.textContent = node.dataset.original || ''; node.blur(); } }; });
}
function commitEdit(node: HTMLElement) { const original = node.dataset.original || ''; const value = node.textContent || ''; if (value === original) return; const slide = currentSlide(); if (!slide) return; try { const kind = node.dataset.editKind; if (kind === 'title') session.commit({ type: 'slides', slideIds: [slide.id] }, [{ type: 'update-slide', slideId: slide.id, changes: { title: value } }], '编辑标题'); else if (kind === 'message') session.commit({ type: 'slides', slideIds: [slide.id] }, [{ type: 'update-slide', slideId: slide.id, changes: { message: value } }], '编辑副标题'); else { const element = slide.elements.find(item => item.id === node.dataset.elementId); if (!element) return; if (kind === 'text') session.commit({ type: 'element', slideId: slide.id, elementId: element.id }, [{ type: 'replace-element', slideId: slide.id, element: { ...element, type: 'text', text: value } }], '编辑文字'); else if (kind === 'bullet') { const items = Array.from(stageEl.querySelectorAll<HTMLElement>('.bullet-item')).map(item => item.textContent?.replace(/^• /, '').trim() || ''); session.commit({ type: 'element', slideId: slide.id, elementId: element.id }, [{ type: 'replace-element', slideId: slide.id, element: { ...element, type: 'bullet-list', items } }], '编辑列表'); } else return; } status = '已保存'; renderDeck(); } catch (error) { status = error instanceof Error ? error.message : String(error); renderDeck(); } }
function commit(action: () => void) { try { action(); status = '已保存'; renderDeck(); } catch (error) { status = error instanceof Error ? error.message : String(error); renderDeck(); } }
document.querySelector<HTMLButtonElement>('#add-slide')!.onclick = () => commit(() => { const slide = createSlide('slide-' + crypto.randomUUID(), session.current.slides.length + 1); session.commit({ type: 'deck' }, [{ type: 'add-slide', slide, afterSlideId: session.current.slides.at(-1)?.id || null }], '新增幻灯片'); selected = session.current.slides.length - 1; });
document.querySelector<HTMLButtonElement>('#delete-slide')!.onclick = () => { const slide = currentSlide(); if (!slide) return; commit(() => { session.commit({ type: 'deck' }, [{ type: 'delete-slide', slideId: slide.id }], '删除幻灯片'); selected = Math.min(selected, Math.max(0, session.current.slides.length - 1)); selectedElementId = null; }); };
document.querySelector<HTMLButtonElement>('#undo')!.onclick = () => commit(() => { if (session.undo()) selected = Math.min(selected, Math.max(0, session.current.slides.length - 1)); selectedElementId = null; });
document.querySelector<HTMLButtonElement>('#redo')!.onclick = () => commit(() => { if (session.redo()) selected = Math.min(selected, Math.max(0, session.current.slides.length - 1)); selectedElementId = null; });
layoutSelect.onchange = () => { const slide = currentSlide(); if (!slide) return; commit(() => session.commit({ type: 'slides', slideIds: [slide.id] }, [{ type: 'update-slide', slideId: slide.id, changes: { layoutId: layoutSelect.value as Slide['layoutId'] } }], '切换布局')); };
selectionEl.onclick = event => { const id = (event.target as HTMLElement).id; const slide = currentSlide(); if (!slide) return; if (id === 'delete-element' && selectedElementId) commit(() => { session.commit({ type: 'element', slideId: slide.id, elementId: selectedElementId! }, [{ type: 'delete-element', slideId: slide.id, elementId: selectedElementId! }], '删除元素'); selectedElementId = null; }); if (id === 'add-text' || id === 'add-list' || id === 'add-citation') commit(() => { const number = slide.elements.length + 1; const element: Element = id === 'add-text' ? { id: crypto.randomUUID(), type: 'text', text: '新增文字' } : id === 'add-list' ? { id: crypto.randomUUID(), type: 'bullet-list', items: ['新增列表项'] } : { id: crypto.randomUUID(), type: 'citation', sourceIds: [fixtureSource.id] }; session.commit({ type: 'slides', slideIds: [slide.id] }, [{ type: 'add-element', slideId: slide.id, element }], '新增元素'); selectedElementId = element.id; }); };
document.querySelector<HTMLButtonElement>('#export')!.onclick = async () => { const snapshot = structuredClone(session.current); try { status = '正在导出'; renderDeck(); const blob = await exportDeck(snapshot, placeholder); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'smartJC-fixture.pptx'; link.click(); URL.revokeObjectURL(url); status = '导出完成'; renderDeck(); } catch (error) { status = error instanceof Error ? error.message : String(error); renderDeck(); } };
document.querySelector<HTMLButtonElement>('#more')!.onclick = () => { status = 'M1 固定 Deck 编辑器'; renderDeck(); };
renderDeck();
