import './style.css';
import { fixtureDeck, fixtureSource } from './fixtures';
import { computeLayout, validateDeck } from './layout';
import { cropCanvas, renderPdf } from './pdf';
import { exportDeck } from './export';
import { readPdfBlob, savePdfBlob } from './storage';

const app = document.querySelector<HTMLDivElement>('#app')!;
let selected = 0; let currentDeck = structuredClone(fixtureDeck); let figureImage = '';
app.innerHTML = `<main class="app"><header><div><h1>smartJC · M0 技术路线验证</h1><div class="meta">PDF.js · 共享归一化几何 · PptxGenJS · IndexedDB Blob</div></div><span class="route">${location.hash || '#/'}</span></header><section class="panel drop"><strong>PDF 输入</strong><div class="actions"><input id="pdf" type="file" accept="application/pdf" /><button id="stored">读取已保存 Blob</button><button id="export">导出固定 Deck PPTX</button></div><div id="status" class="status">请选择代表性 PDF；固定 Deck 可直接预览与导出。</div><canvas id="pdf-canvas" hidden></canvas></section><section class="grid"><aside class="panel"><h3>固定 Deck fixture</h3><div id="slides" class="slides"></div><div class="meta">3 页 · schemaVersion 1 · revision 0</div></aside><section class="panel"><h3 id="heading"></h3><div id="stage" class="stage"></div><div class="actions"><button id="crop">按 Source bbox 裁图</button><button id="reset">重置 fixture</button></div><div id="layout" class="status"></div></section><aside class="panel"><h3>验证结果</h3><div class="checklist"><div>✓ 固定 Deck 与六类布局契约</div><div>✓ Web/PPTX 共用归一化框</div><div id="pdf-check">○ PDF.js 文本与页渲染</div><div id="blob-check">○ IndexedDB 原 PDF Blob</div><div>○ 模型候选浏览器直连（待 Key/CORS 实测）</div><div>○ GitHub Pages 子路径（待远程仓库）</div></div></aside></section></main>`;
const slidesEl = document.querySelector<HTMLDivElement>('#slides')!; const stageEl = document.querySelector<HTMLDivElement>('#stage')!; const heading = document.querySelector<HTMLHeadingElement>('#heading')!; const status = document.querySelector<HTMLDivElement>('#status')!; const layoutStatus = document.querySelector<HTMLDivElement>('#layout')!; const canvas = document.querySelector<HTMLCanvasElement>('#pdf-canvas')!;
function renderDeck() { const slide = currentDeck.slides[selected]; slidesEl.innerHTML = currentDeck.slides.map((s, i) => `<button class="slide-btn ${i === selected ? 'active' : ''}" data-index="${i}">${String(i + 1).padStart(2, '0')} · ${s.title}</button>`).join(''); slidesEl.querySelectorAll<HTMLButtonElement>('button').forEach(b => b.onclick = () => { selected = Number(b.dataset.index); renderDeck(); }); if (!slide) { heading.textContent = ''; stageEl.innerHTML = '<div class="meta">没有幻灯片</div>'; return; } heading.textContent = slide.title; const layout = computeLayout(slide); stageEl.innerHTML = `<div class="stage-title" style="left:${layout.title.x * 100}%;top:${layout.title.y * 100}%;width:${layout.title.width * 100}%">${slide.title}</div>${layout.message ? `<div class="stage-message" style="left:${layout.message.x * 100}%;top:${layout.message.y * 100}%;width:${layout.message.width * 100}%">${slide.message}</div>` : ''}${layout.elements.map(({ element, rect }) => { const style = `left:${rect.x * 100}%;top:${rect.y * 100}%;width:${rect.width * 100}%;height:${rect.height * 100}%`; if (element.type === 'figure') return `<img src="${figureImage || 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22800%22 height=%22480%22%3E%3Crect width=%22800%22 height=%22480%22 fill=%22%23dcebf2%22/%3E%3Ctext x=%22240%22 y=%22250%22 font-size=%2240%22 fill=%22%232878a8%22%3EFigure 3%3C/text%3E%3C/svg%3E'}" style="${style}" alt="Figure 3 fixture"/>`; if (element.type === 'bullet-list') return `<div class="stage-text" style="${style}">${element.items.map(x => `• ${x}`).join('<br/>')}</div>`; return `<div class="stage-text" style="${style}">${element.text}</div>`; }).join('')}<div class="source-label">来源：PDF page 1 · bbox (.12, .20, .76, .58) · ${fixtureSource.id}</div>`; layoutStatus.textContent = `布局 ${slide.layoutId} · ${layout.elements.length} 个元素 · ${validateDeck(currentDeck).length ? '校验失败' : '结构校验通过'} · Web/PPTX 共用归一化框`; }
renderDeck();
document.querySelector<HTMLInputElement>('#pdf')!.onchange = async e => { const file = (e.target as HTMLInputElement).files?.[0]; if (!file) return; try { await savePdfBlob(file); const result = await renderPdf(await file.arrayBuffer(), canvas); canvas.hidden = false; figureImage = canvas.toDataURL('image/png'); document.querySelector('#pdf-check')!.textContent = `✓ PDF.js ${result.pages} 页、文本 ${result.text.length} 字符、首页面渲染`; document.querySelector('#blob-check')!.textContent = `✓ IndexedDB Blob 已写入（${Math.round(file.size / 1024)} KB）`; status.textContent = 'PDF.js 页面、文字和 Blob 检查完成；可按 Source bbox 裁图。'; renderDeck(); } catch (error) { status.textContent = `PDF 失败：${error instanceof Error ? error.message : String(error)}`; } };
document.querySelector<HTMLButtonElement>('#stored')!.onclick = async () => { const blob = await readPdfBlob(); status.textContent = blob ? `IndexedDB Blob 重读成功：${Math.round(blob.size / 1024)} KB` : '尚无已保存 PDF Blob'; };
document.querySelector<HTMLButtonElement>('#crop')!.onclick = () => { if (!canvas.width) { status.textContent = '请先选择 PDF 再裁图'; return; } figureImage = cropCanvas(canvas, fixtureSource.bbox); status.textContent = '已按 Source bbox 裁图；只更新当前预览 Figure，不改变共享来源。'; renderDeck(); };
document.querySelector<HTMLButtonElement>('#reset')!.onclick = () => { currentDeck = structuredClone(fixtureDeck); selected = 0; figureImage = ''; renderDeck(); status.textContent = 'fixture 已重置'; };
document.querySelector<HTMLButtonElement>('#export')!.onclick = async () => { try { const blob = await exportDeck(currentDeck, figureImage || 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iNDAwIj48cmVjdCB3aWR0aD0iODAwIiBoZWlnaHQ9IjQwMCIgZmlsbD0iI2RjZWJmMiIvPjwvc3ZnPg=='); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'smartJC-fixture.pptx'; a.click(); URL.revokeObjectURL(url); status.textContent = 'PPTX 导出完成（文字为文本对象，Figure 为等比图片）。'; } catch (error) { status.textContent = `导出失败：${error instanceof Error ? error.message : String(error)}`; } };
window.addEventListener('hashchange', () => { document.querySelector('.route')!.textContent = location.hash || '#/'; });
